# Generated by Django 3.0.3 on 2020-07-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Paste your image URL', max_length=1000)),
                ('image_title', models.CharField(help_text='Give your image title', max_length=200)),
                ('image_type', models.CharField(choices=[('personal', 'Personal'), ('customized', 'Customized')], help_text='Image Type could be Personal or Customized', max_length=100)),
                ('site_name', models.CharField(help_text='The name of the site you copy image URL', max_length=100)),
                ('your_name', models.CharField(help_text='Your name on the site you copy image URL', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('comment', models.TextField(help_text='Describe your image and give good expression about us', max_length=1000, verbose_name='Comment On Your Image')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePostReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_member_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ordinary_member_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image Poster Reward',
            },
        ),
        migrations.CreateModel(
            name='ImageViewCountDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image View Count Down',
            },
        ),
        migrations.CreateModel(
            name='ImageViewReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_viewer_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ordinary_viewer_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image View Reward',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.CharField(blank=True, max_length=100, null=True)),
                ('display_till', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='image.Image')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'View Table',
            },
        ),
    ]
