# Generated by Django 3.0.3 on 2020-07-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
