# Generated by Django 3.0.3 on 2020-07-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20200727_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageViewLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image View Daily Limit',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(help_text='Paste your image URL', max_length=1000, unique=True),
        ),
    ]
