# Generated by Django 3.0.3 on 2020-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20200729_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageviewlimit',
            options={'verbose_name_plural': 'Image Daily View Limit'},
        ),
        migrations.AlterField(
            model_name='viewer',
            name='date_viewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
