# Generated by Django 3.0.3 on 2020-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approve'), ('Declined', 'Decline')], max_length=10),
        ),
    ]
