# Generated by Django 3.0.3 on 2020-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_comment_commentbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
