# Generated by Django 3.0.3 on 2020-06-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200608_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUserReferUpgradeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Premium User Refer Upgrade Bonus',
            },
        ),
    ]
