# Generated by Django 3.0.3 on 2020-06-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bloglike_bloglikebonus_premiumbloglikebonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloglike',
            options={'verbose_name_plural': 'Blog Likes'},
        ),
    ]
