# Generated by Django 3.0.3 on 2020-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200622_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageViewCountDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image View Count Down',
            },
        ),
        migrations.CreateModel(
            name='ImageViewReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_image_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('ordinary_image_reward', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image View Reward',
            },
        ),
    ]
