# Generated by Django 3.0.3 on 2020-07-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_imageviewcountdown_imageviewreward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageViewCountDown',
        ),
        migrations.DeleteModel(
            name='ImageViewReward',
        ),
    ]
